version: '3.8'

services:
  mcp-minecraft-mcpc:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MCP_SERVER_NAME=mcp-minecraft-mcpc-1.6.4
      - MCP_SERVER_VERSION=1.0.0
      - MAX_FILE_SIZE=10MB
      - MAX_SPRITES_PER_ATLAS=100
      - DEFAULT_ATLAS_SIZE=1024
      - LOG_LEVEL=info
      - ENABLE_REQUEST_LOGGING=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
