# Configuration Nixpacks pour Railway
# Ce fichier indique à Railway de déployer depuis le dossier server/

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && npm run build"]

[start]
cmd = "cd server && npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"
MCP_SERVER_NAME = "mcp-minecraft-gui"
MCP_SERVER_VERSION = "1.0.0"
MAX_FILE_SIZE = "10MB"
MAX_SPRITES_PER_ATLAS = "100"
DEFAULT_ATLAS_SIZE = "1024"
LOG_LEVEL = "info"
ENABLE_REQUEST_LOGGING = "true"
